import { Inter, Krona_One, Trirong } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav";

const inter = Inter({ subsets: ["latin"] });
const kronaOne = Krona_One({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-krona-one',
});
const trirong = Trirong({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-trirong',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${kronaOne.variable} ${trirong.variable}`}>
      <body className={`w-full bg-white ${inter.className}`}>
        <Nav/>
        {children}
      </body>
    </html>
  );
}